version: '3.7'
services:  
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'crm_aprofem'
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
    links:
      - db
    networks:
      - default
    depends_on:
      - db
  db:
    image: mariadb:10.3.34
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - default
